CREATE TABLE MEMBER(
 ID VARCHAR2(10) PRIMARY KEY,
 PASSWORD VARCHAR2(100),
 NAME VARCHAR2(30),
 ROLE VARCHAR2(12),
 ENABLED BOOLEAN -- 해당 계정 활성화/비활성화 판단할때 사용
);
INSERT INTO MEMBER VALUES('member', 'member123','회원','ROLE_MEMBER', TRUE);
INSERT INTO MEMBER  VALUES('manager', 'manager123','매니저','ROLE_MANAGER', TRUE);
INSERT INTO MEMBER VALUES('admin', 'admin123','어드민','ROLE_ADMIN', TRUE);